//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClubLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDetail
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Home_Phone { get; set; }
        public string Mobile { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public bool Enable { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }

       
    }
}
