//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityLib.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyClubSecurity : DbContext
    {
        public MyClubSecurity()
            : base("name=MyClubSecurity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User_Profile> User_Profiles { get; set; }
        public virtual DbSet<WebPages_Pages> WebPages_Pages { get; set; }
        public virtual DbSet<webPages_UserPermessions> webPages_UserPermessions { get; set; }
    }
}
